//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadonban()
        {
            this.chitiethdbs = new HashSet<chitiethdb>();
        }
    
        public string mahdb { get; set; }
        public string maNV { get; set; }
        public string maKH { get; set; }
        public Nullable<System.DateTime> ngayBan { get; set; }
        public string hinhthucthanhtoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethdb> chitiethdbs { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
