//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA1_WF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DA1_WF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _301783299_505977474861885_7635328122871902833_n {
            get {
                object obj = ResourceManager.GetObject("301783299_505977474861885_7635328122871902833_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5087592 {
            get {
                object obj = ResourceManager.GetObject("5087592", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _54681549_a00f_4ad5_9e1e_e56f2a01fc52 {
            get {
                object obj = ResourceManager.GetObject("54681549-a00f-4ad5-9e1e-e56f2a01fc52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bill {
            get {
                object obj = ResourceManager.GetObject("bill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bill_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("bill-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_cosmetics_clip_art_foundation_transparency_vector_make_up_svg_vector_icon_free_icons_uihere_5cf0a95f1b9993_9820024015592758711131 {
            get {
                object obj = ResourceManager.GetObject("kisspng-cosmetics-clip-art-foundation-transparency-vector-make-up-svg-vector-icon" +
                        "-free-icons-uihere-5cf0a95f1b9993.9820024015592758711131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_payment_card_credit_card_computer_icons_cheque_payment_icon_credit_payment_icon_5ab07ae60116e8_8012353815215152380045 {
            get {
                object obj = ResourceManager.GetObject("kisspng-payment-card-credit-card-computer-icons-cheque-payment-icon-credit-paymen" +
                        "t-icon-5ab07ae60116e8.8012353815215152380045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_payment_card_credit_card_computer_icons_cheque_payment_icon_credit_payment_icon_5ab07ae60116e8_8012353815215152380045_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-payment-card-credit-card-computer-icons-cheque-payment-icon-credit-paymen" +
                        "t-icon-5ab07ae60116e8.8012353815215152380045-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_payment_card_credit_card_money_payment_5acaeb411859b1_7792140715232479370998 {
            get {
                object obj = ResourceManager.GetObject("kisspng-payment-card-credit-card-money-payment-5acaeb411859b1.7792140715232479370" +
                        "998", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_payment_card_credit_card_money_payment_5acaeb411859b1_7792140715232479370998_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-payment-card-credit-card-money-payment-5acaeb411859b1.7792140715232479370" +
                        "998-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_portable_network_graphics_computer_icons_cosmetics_voce_svg_png_icon_free_download_38_678_online_5c6cb1b49ebf95_8850818415506272526502 {
            get {
                object obj = ResourceManager.GetObject("kisspng-portable-network-graphics-computer-icons-cosmetics-voce-svg-png-icon-free" +
                        "-download-38-678-online-5c6cb1b49ebf95.8850818415506272526502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_statistics_computer_icons_statistics_icon_5b4574b685ccc4_9604191915312785185481 {
            get {
                object obj = ResourceManager.GetObject("kisspng-statistics-computer-icons-statistics-icon-5b4574b685ccc4.9604191915312785" +
                        "185481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_statistics_computer_icons_statistics_icon_5b4574b685ccc4_9604191915312785185481_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-statistics-computer-icons-statistics-icon-5b4574b685ccc4.9604191915312785" +
                        "185481-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_statistics_computer_icons_statistics_icon_5b4574b685ccc41 {
            get {
                object obj = ResourceManager.GetObject("kisspng-statistics-computer-icons-statistics-icon-5b4574b685ccc41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_invoice_price_icon_library_invoices_miscellaneous_text {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-invoice-price-icon-library-invoices-miscellaneous-text" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_invoice_price_icon_library_invoices_miscellaneous_text1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-invoice-price-icon-library-invoices-miscellaneous-text" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_statistics_bar_chart_histogram_statistics_miscellaneous_angle_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-statistics-bar-chart-histogram-statistics-miscellaneou" +
                        "s-angle-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_credit_card_computer_icons_payment_bank_credit_card_angle_text {
            get {
                object obj = ResourceManager.GetObject("png-clipart-credit-card-computer-icons-payment-bank-credit-card-angle-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_logo_computer_icons_text_writing_icon_angle_text_thumbnail_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-logo-computer-icons-text-writing-icon-angle-text-thumbnail-removebg-p" +
                        "review", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_makeup_brush_computer_icons_blush_material_cdr_holidays_cosmetics {
            get {
                object obj = ResourceManager.GetObject("png-transparent-makeup-brush-computer-icons-blush-material-cdr-holidays-cosmetics" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_fresh_hand_painted_cosmetics_combination_png_image_1659787 {
            get {
                object obj = ResourceManager.GetObject("pngtree-fresh-hand-painted-cosmetics-combination-png-image_1659787", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_fresh_hand_painted_cosmetics_combination_png_image_4971081 {
            get {
                object obj = ResourceManager.GetObject("pngtree-fresh-hand-painted-cosmetics-combination-png-image_4971081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_invoice_icon_png_image_1817550_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-invoice-icon-png-image_1817550-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_candy_icon_png_image_1638394 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-candy-icon-png-image_1638394", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_statistics_icon_png_image_322171 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-statistics-icon-png-image_322171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sản_phẩm {
            get {
                object obj = ResourceManager.GetObject("sản phẩm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sodapdf_converted {
            get {
                object obj = ResourceManager.GetObject("sodapdf-converted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống {
            get {
                object obj = ResourceManager.GetObject("tải xuống", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống__1_ {
            get {
                object obj = ResourceManager.GetObject("tải xuống (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống1 {
            get {
                object obj = ResourceManager.GetObject("tải xuống1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống2 {
            get {
                object obj = ResourceManager.GetObject("tải xuống2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_sign_icon_person_symbol_human_avatar_isolated_on_white_backogrund_vector {
            get {
                object obj = ResourceManager.GetObject("user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_sign_icon_person_symbol_human_avatar_isolated_on_white_backogrund_vector1 {
            get {
                object obj = ResourceManager.GetObject("user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
